class JSON:

    """
    Game related keys.
    """
    games = "games"
    id = "id"
    season = "season"
    game_type = "gameType"
    game_state = "gameState"
    player_by_game_stats = "playerByGameStats"
    
    
    home_team = "homeTeam"
    away_team = "awayTeam"
    forwards = "forwards"
    defense = "defense"
    goalies = "goalies"

    """
    Stat related keys
    """
    goals = "goals"
    assists = "assists"
    points = "points"
    plus_minus = "plusMinus"
    pim = "pim"
    hits = "hits"
    power_play_goals = "powerPlayGoals"
    sog = "sog"
    faceoff_winning_pctg = "faceoffWinningPctg"
    toi = "toi"
    blocked_shots = "blockedShots"
    shifts = "shifts"
    giveaways = "giveaways"
    takeaways = "takeaways"
    even_strength_shots_against = "evenStrengthShotsAgainst"
    power_play_shots_against = "powerPlayShotsAgainst"
    shorthanded_shots_against = "shorthandedShotsAgainst"
    save_shots_against = "saveShotsAgainst"
    save_pctg = "savePctg"
    even_strength_goals_against = "evenStrengthGoalsAgainst"
    power_play_goals_against = "powerPlayGoalsAgainst"
    shorthanded_goals_against = "shorthandedGoalsAgainst"
    goals_against = "goalsAgainst"
    starter = "starter"
    decision = "decision"
    shots_against = "shotsAgainst"
    saves = "saves"

    """
    Player related keys
    """
    player_id = "playerId"
    game_id = "gameId"